export const theme = Object.freeze({
  colors: {
    black: '#000',
    white: '#fff',
    red: '#FF0000',
    green: '#008000',
    textOne: '#adb5bf',
    textTwo: '#535557',
    bgOne: '#e7ecf2',
    bgTwo: '#f1f2f6',
    bgStats: '#f3f6f9',
    primary: '#07c',
    secondary: '#05a',
    accent: '#609',
    muted: '#f6f6f6',
  },
  space: [0, 2, 4, 8, 16, 32, 64, 128, 256],
  fonts: {
    body: 'system-ui, sans-serif',
    heading: 'system-ui, sans-serif',
    monospace: 'Menlo, monospace',
  },
  fontSizes: {
    xs: '12px',
    s: '14px',
    m: '16px',
    xm: '24px',
    l: '32px',
    xl: '64px',
  },
  fontWeights: {
    normal: 400,
    medium: 550,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  borders: {
    none: 'none',
    normal: '1px solid',
  },
  radii: {
    none: '0',
    sm: '4px',
    md: '8px',
    lg: '16px',
    round: '50%',
  },
});
